@base = https://localhost:8443/api 

#### Login
# @name login 
POST {{base}}/auth/login
Content-Type: application/json

{
    "userName": "tom",
    "password": "password"
}

#### 
POST {{base}}/books/maths/questions/CHOOSE_THE_BEST/part-1/sets-relations-functions
Authorization: Bearer {{login.response.body.authToken}}
Content-Type: application/json

{
	"question": "\\\\(A=\\lbrace (x,y):Y=e^x,x \\in \\R \\rbrace \\\\) - மற்றும் \\\\(B=\\lbrace (x,y):Y=e^-x,x \\in \\R \\rbrace \\\\) எனில், \\\\(n(A \\cap B)\\\\) என்பது",
	"type": "CHOOSE_THE_BEST",
	"choices": [{
		"value": "\\( \\infty \\)"
	}, {
		"value": "0"
	}, {
		"value": "1",
		"answer": true
	}, {
		"value": "2"
	}]
}

#### 
POST {{base}}/books/maths/questions/CHOOSE_THE_BEST/part-1/sets-relations-functions
Authorization: Bearer {{login.response.body.authToken}}
Content-Type: application/json

{
	"question": "\\\\(A=\\lbrace (x,y):y=sin x,x \\in \\R \\rbrace \\\\), மற்றும்\\\\(A=\\lbrace (x,y):y=cos x,x \\in \\R \rbrace \\\\), எனில், \\\\(A \\cap B\\\\)- ல்",
	"type": "CHOOSE_THE_BEST",
	"choices": [{
		"value": "உறுப்புகளில்லை"
	}, {
		"value": "எண்ணிலடங்கா உறுப்புகள் உள்ளன",
		"answer": true
	}, {
		"value": "ஓரே ஒரு உறுப்பு உள்ளது"
	}, {
		"value": "தீர்மானிக்க இயலாது"
	}]
}

#### 
POST {{base}}/books/maths/questions/CHOOSE_THE_BEST/part-1/sets-relations-functions
Authorization: Bearer {{login.response.body.authToken}}
Content-Type: application/json

{
	"question": "\\\\(A = {0, -1, 1, 2}\\\\) எனும் கணத்தில் \\\\(|x^2 + y^2| \\leq 2 \\\\) எனுமாறு \\\\(xRy\\\\) ஆக வரையறுக்கப்பட்ட தொடர்பு R எனில், கீழ்க்கண்டவற்றில் எது சரியானது ?",
	"type": "CHOOSE_THE_BEST",
	"choices": [{
		"value": "\\(R = \\lbrace ( 0 , 0 ), ( 0 , – 1 ), ( 0 , 1 ), ( – 1 , 0 ), ( – 1 , 1 ), ( 1 , 2 ), ( 1 , 0 ) \\rbrace \\)"
	}, {
		"value": "\\(R -1 = \\lbrace( 0 , 0 ), ( 0 , – 1 ), ( 0 , 1 ), ( – 1 , 0 ), ( 1 , 0 )\\rbrace \\)"
	}, {
		"value": "\\(R - ன்  சார்பகம்  \\lbrace 0, -1, 1, 2 \\rbrace \\)"
	}, {
		"value": "\\(R - ன்  வீச்சகம்  \\lbrace 0, -1, 1 \\rbrace \\)",
		"answer": true
	}]
}

#### 
POST {{base}}/books/maths/questions/CHOOSE_THE_BEST/part-1/sets-relations-functions
Authorization: Bearer {{login.response.body.authToken}}
Content-Type: application/json

{
	"question": "\\\\(A = {0, -1, 1, 2}\\\\) எனும் கணத்தில் \\\\(|x^2 + y^2| \\leq 2 \\\\) எனுமாறு \\\\(xRy\\\\) ஆக வரையறுக்கப்பட்ட தொடர்பு R எனில், கீழ்க்கண்டவற்றில் எது சரியானது ?",
	"type": "CHOOSE_THE_BEST",
	"choices": [{
		"value": "\\(R = \\lbrace ( 0 , 0 ), ( 0 , – 1 ), ( 0 , 1 ), ( – 1 , 0 ), ( – 1 , 1 ), ( 1 , 2 ), ( 1 , 0 ) \\rbrace \\)",
		"answer": true
	}, {
		"value": "\\(R -1 = \\lbrace( 0 , 0 ), ( 0 , – 1 ), ( 0 , 1 ), ( – 1 , 0 ), ( 1 , 0 )\\rbrace \\)"
	}, {
		"value": "\\(R - ன்  சார்பகம்  \\lbrace 0, -1, 1, 2 \\rbrace \\)"
	}, {
		"value": "\\(R - ன்  வீச்சகம்  \\lbrace 0, -1, 1 \\rbrace \\)"
	}]
}

#### 
POST {{base}}/books/maths/questions/CHOOSE_THE_BEST/part-1/sets-relations-functions
Authorization: Bearer {{login.response.body.authToken}}
Content-Type: application/json

{
	"question": "\\\\(\\R\\\\) மெய்யெண்களின் கணம் என்க. \\\\( \\R × \\R \\\\) –ல் கீழ்க்கண்ட உட்கணங்களைக் கருதுக. \\\\(S = \\lbrace (x , y): y = x + 1\\\\) மற்றும் \\\\(0 < x < 2 \\rbrace ; T = \\lbrace ( x , y ) : x – y \\in  \\Z \\\\) எனில் கீழ்க்காணும் கூற்றில் எது மெய்யானது?)",
	"type": "CHOOSE_THE_BEST",
	"choices": [{
		"value": "T சமானத் தொடர்பு ஆனால், S சமானத் தொடர்பு அல்ல.",
		"answer": true
	}, {
		"value": "S , T இரண்டுமே சமானத் தொடர்பு அல்ல."
	}, {
		"value": "S, T இரண்டுமே சமானத் தொடர்பு."
	}, {
		"value": "S சமானத் தொடர்பு ஆனால், T சமானத் தொடர்பு அல்ல."
	}]
}

#### 
POST {{base}}/books/maths/questions/CHOOSE_THE_BEST/part-1/sets-relations-functions
Authorization: Bearer {{login.response.body.authToken}}
Content-Type: application/json

{
	"question": "இயல் எண்களின் அனைத்துக்கணம்  \\\\( \\N \\\\) - க்கு  A மற்றும் B உட்கணங்கள் எனில் \\\\(A^{'} \\cup [(A \\cap B ) \\cup B^{'}] \\\\) என்பது",
	"type": "CHOOSE_THE_BEST",
	"choices": [{
		"value": "A"
	}, {
		"value": "\\(A^{'}\\)"
	}, {
		"value": "B"
	}, {
		"value": "\\( \\N \\)",
		"answer": true
	}]
}

#### 
POST {{base}}/books/maths/questions/CHOOSE_THE_BEST/part-1/sets-relations-functions
Authorization: Bearer {{login.response.body.authToken}}
Content-Type: application/json

{
	"question": "கணிதம் மற்றும் வேதியியல் இரண்டும் பாடங்களாக ஏற்ற மாணவர்களின் எண்ணிக்கை 70.இது கணிதத்தை ஏற்றவர்களின் 10% மற்றும் வேதியியல் ஏற்றவர்களின் 14% ஆகும்.இவற்றில் ஏதாவதொன்றைப் பாடமாக ஏற்ற மாணவர்களின் எண்ணிக்கை",
	"type": "CHOOSE_THE_BEST",
	"choices": [{
		"value": "1120"
	}, {
		"value": "1130",
		"answer": true
	}, {
		"value": "1100"
	}, {
		"value": "போதுமான தகவல் இல்லை."
	}]
}

#### 
POST {{base}}/books/maths/questions/CHOOSE_THE_BEST/part-1/sets-relations-functions
Authorization: Bearer {{login.response.body.authToken}}
Content-Type: application/json

{
	"question": "\\( n[ (A \times B) \\cap (A \times C) ) ] = 8  மற்றும்   n (B \\cap C) = 2  எனில், \\ n(A)\\\\) என்பது",
	"type": "CHOOSE_THE_BEST",
	"choices": [{
		"value": "6"
	}, {
		"value": "4",
		"answer": true
	}, {
		"value": "8"
	}, {
		"value": "16"
	}]
}

#### 
POST {{base}}/books/maths/questions/CHOOSE_THE_BEST/part-1/sets-relations-functions
Authorization: Bearer {{login.response.body.authToken}}
Content-Type: application/json

{
	"question": "\\\\( n(A)= 2 \\ மற்றும் \\ n(B \\cup C = 3 , எனில் n [( A \times B ) \\cup ( A \times C )]\\\\) என்பது",
	"choices": [{
		"value": "\\(1^3\\)"
	}, {
		"value": "\\(3^2\\)"
	}, {
		"value": "6",
		"answer": true
	}, {
		"value": "5"
	}]
}

#### 
POST {{base}}/books/maths/questions/CHOOSE_THE_BEST/part-1/sets-relations-functions
Authorization: Bearer {{login.response.body.authToken}}
Content-Type: application/json

{
	"question": "A மற்றும் B எனும் இரு கணங்களில் 17 உறுப்புகள் பொதுவானவை எனில், \\\\(A \\times B \\\\) மற்றும் \\\\(B \\times A \\\\) ஆகிய கணங்களில் உள்ள பொது உறுப்புகளின் எண்ணிக்கை",
	"choices": [{
		"value": "\\(2^{17}\\)"
	}, {
		"value": "\\(17^2\\)",
		"answer": true
	}, {
		"value": "34"
	}, {
		"value": "போதுமான தகவல் இல்லை"
	}]
}

#### 
POST {{base}}/books/maths/questions/CHOOSE_THE_BEST/part-1/sets-relations-functions
Authorization: Bearer {{login.response.body.authToken}}
Content-Type: application/json

{
	"question": "வெற்றற்ற கணங்கள் A மற்றும் B என்க. \\\\(A \\subset B \\\\) எனில் \\\\( (A \\times B) \\cap (B \\times A) =\\\\)",
	"choices": [{
		"value": "\\(A \\cap B\\)"
	}, {
		"value": "\\(A \times A\\)",
		"answer": true
	}, {
		"value": "\\(B \times B\\)"
	}, {
		"value": "இவற்றுள் எதுவும் இல்லை"
	}]
}

#### 
POST {{base}}/books/maths/questions/CHOOSE_THE_BEST/part-1/sets-relations-functions
Authorization: Bearer {{login.response.body.authToken}}
Content-Type: application/json

{
	"question": "3 உறுப்புகள் கொண்ட கணத்தின் மீதான தொடர்புகளின் எண்ணிக்கை",
	"choices": [{
		"value": "9"
	}, {
		"value": "81"
	}, {
		"value": "512",
		"answer": true
	}, {
		"value": "1024"
	}]
}

#### 
POST {{base}}/books/maths/questions/CHOOSE_THE_BEST/part-1/sets-relations-functions
Authorization: Bearer {{login.response.body.authToken}}
Content-Type: application/json

{
	"question": "ஒன்றுக்கு மேற்பட்ட உறுப்புகளைக் கொண்ட கணம் X - ன் மீதான அனைத்துத்தொடர்பு R எனில் R என்பது",
	"choices": [{
		"value": "தற்சுட்டுத் தொடர்பு அல்ல"
	}, {
		"value": "சமச்சீர் தொடர்பல்ல"
	}, {
		"value": "கடப்புத் தொடர்பு",
		"answer": true
	}, {
		"value": "இவற்றுள் எதுவுமன்று"
	}]
}

#### 
POST {{base}}/books/maths/questions/CHOOSE_THE_BEST/part-1/sets-relations-functions
Authorization: Bearer {{login.response.body.authToken}}
Content-Type: application/json

{
	"question": "\\\\(X = \\lbrace 1, 2, 3, 4 \\rbrace\\\\) மற்றும் \\\\( R= \\lbrace (1,1),(1,2),(1,3),(2,2),(3,3),(2,1),(3,1),(1,4),(4,1) \\rbrace \\\\) எனில் R என்பது",
	"choices": [{
		"value": "தற்சுட்டுத் தொடர்பு"
	}, {
		"value": "சமச்சீர் தொடர்பு",
		"answer": true
	}, {
		"value": "கடப்புத் தொடர்பு"
	}, {
		"value": "சமானத் தொடர்பு"
	}]
}

#### 
POST {{base}}/books/maths/questions/CHOOSE_THE_BEST/part-1/sets-relations-functions
Authorization: Bearer {{login.response.body.authToken}}
Content-Type: application/json

{
	"question": "\\\\( \\dfrac {1} {1- 2 sinx} \\\\) என்ற சார்பின் வீச்சகம்",
	"choices": [{
		"value": "\\((- \\infty ,-1)\\cup ( \\dfrac {1}{3},\\infty)\\)"
	}, {
		"value": "\\(\\big(-1, \\dfrac {1}{3}\\big)\\)"
	}, {
		"value": "\\( \\big[ - 1 , \\dfrac {1}{3} \\big] \\)"
	}, {
		"value": "\\( (- \\infty , - 1),\\cup \\big[ \\dfrac{1}{3},\\infty) \\)",
		"answer": true
	}]
}

#### 
POST {{base}}/books/maths/questions/CHOOSE_THE_BEST/part-1/sets-relations-functions
Authorization: Bearer {{login.response.body.authToken}}
Content-Type: application/json

{
	"question": "\\\\( f (x) = | [ x ]-x | ,x \\in \\R\\\\) என்ற சார்பின் வீச்சகம்",
	"choices": [{
		"value": "[0, 1]"
	}, {
		"value": "\\([0, \\infty )\\)"
	}, {
		"value": "[0, 1)",
		"answer": true
	}, {
		"value": "(0, 1)"
	}]
}

#### 
POST {{base}}/books/maths/questions/CHOOSE_THE_BEST/part-1/sets-relations-functions
Authorization: Bearer {{login.response.body.authToken}}
Content-Type: application/json

{
	"question": "\\\\(f(x) = x^2\\\\) என்ற சார்பு இருபுறச் சார்பாக அமைய வேண்டுமெனில் அதன் சார்பகமும்,துணைச்சார்பகமும் முறையே",
	"choices": [{
		"value": "\\(\\R,\\R\\)"
	}, {
		"value": "\\(\\R,(0,-\\infty)\\)"
	}, {
		"value": "\\((0, -\\infty ),\\R\\)"
	}, {
		"value": "\\([0, \\infty), [0, \\infty)\\)",
		"answer": true
	}]
}

#### 
POST {{base}}/books/maths/questions/CHOOSE_THE_BEST/part-1/sets-relations-functions
Authorization: Bearer {{login.response.body.authToken}}
Content-Type: application/json

{
	"question": "m உறுப்புகள் கொண்ட ஒரு கணத்திலிருந்து n உறுப்புகள்  கொண்ட ஒரு கணத்திற்கு வரையறுக்கப்படும் மாறிலிச் சார்புகளின் எண்ணிக்கை",
	"choices": [{
		"value": "mn"
	}, {
		"value": "m"
	}, {
		"value": "n",
		"answer": true
	}, {
		"value": "m+n"
	}]
}

#### 
POST {{base}}/books/maths/questions/CHOOSE_THE_BEST/part-1/sets-relations-functions
Authorization: Bearer {{login.response.body.authToken}}
Content-Type: application/json

{
	"question": "\\\\( f:[ 0 , 2 \\pi ] \\rightarrow  [ – 1 , 1 ] \\\\)என்ற சார்பு, \\\\(f(x)= sin x\\\\) என வரையறுக்கப்படுகிறது எனில், அது",
	"choices": [{
		"value": "ஒன்றுக்கொன்று "
	}, {
		"value": "மேற்கோர்த்தல்",
		"answer": true
	}, {
		"value": "இருபுறச் சார்பு"
	}, {
		"value": "வரையறுக்க இயலாது"
	}]
}

#### 
POST {{base}}/books/maths/questions/CHOOSE_THE_BEST/part-1/sets-relations-functions
Authorization: Bearer {{login.response.body.authToken}}
Content-Type: application/json

{
	"question": "\\\\(f : [ – 3 , 3 ] \\rightarrow \\ S \\ என்ற \\ சார்பு \\ f(x) = x^2\\\\) என வறையறுக்கப்பட்டு மேற்கோர்த்தல் எனில், S என்பது",
	"choices": [{
		"value": "[-9, 9] "
	}, {
		"value": "\\(\\R\\)"
	}, {
		"value": "[-3, 3]"
	}, {
		"value": "[0, 9]",
		"answer": true
	}]
}

#### 
POST {{base}}/books/maths/questions/CHOOSE_THE_BEST/part-1/sets-relations-functions
Authorization: Bearer {{login.response.body.authToken}}
Content-Type: application/json

{
	"question": "\\\\(X = \\lbrace 1 , 2 , 3 , 4 \\rbrace , Y = \\lbrace a, b , c , d \\rbrace , \\ மற்றும் \\  f=\\lbrace (1,a),(4,b),(2,c),(3,d),(2,d)\\rbrace\\\\)  எனில் f என்பது",
	"choices": [{
		"value": "ஒன்றுக்கொன்றானச் சார்பு "
	}, {
		"value": "மேற்கோர்த்தல் சார்பு"
	}, {
		"value": "ஒன்றுக்கொன்று அல்லாத சார்பு"
	}, {
		"value": "சார்பன்று",
		"answer": true
	}]
}

#### 
POST {{base}}/books/maths/questions/CHOOSE_THE_BEST/part-1/sets-relations-functions
Authorization: Bearer {{login.response.body.authToken}}
Content-Type: application/json

{
	"question": "\\\\(f : \\R \\rightarrow \\R \\\\)–ல் சார்பு \\\\(f(x) = 1 – |x|\\\\) என வரையறுக்கப்படுகிறது எனில் \\\\(f\\\\) - ன் வீச்சகம்",
	"choices": [{
		"value": "\\(\\R\\) "
	}, {
		"value": "\\((1, \\infty )\\)"
	}, {
		"value": "\\((-1, \\infty )\\)"
	}, {
		"value": "\\((- \\infty , 1]\\)",
		"answer": true
	}]
}

#### 
POST {{base}}/books/maths/questions/CHOOSE_THE_BEST/part-1/sets-relations-functions
Authorization: Bearer {{login.response.body.authToken}}
Content-Type: application/json

{
	"question": "\\\\(f : \\R \\rightarrow \\R \\\\)- ல்  \\\\(f(x) =sin x + cos x\\\\)எனில் f ஆனது",
	"choices": [{
		"value": "ஒரு ஒற்றைப்படைச் சார்பு "
	}, {
		"value": "ஒற்றைப்படையுமல்ல இரட்டைப்படையுமல்ல",
		"answer": true
	}, {
		"value": "ஒரு இரட்டைப்படைச் சார்பு)"
	}, {
		"value": "ஒற்றைப்படை மற்றும் இரட்டைப்படைச் சார்பு"
	}]
}

#### 
POST {{base}}/books/maths/questions/CHOOSE_THE_BEST/part-1/sets-relations-functions
Authorization: Bearer {{login.response.body.authToken}}
Content-Type: application/json

{
	"question": "\\\\(f : \\R \\rightarrow \\R \\\\)- ல்  \\\\(f(x) =\\dfrac{(x^2+cos \\ x)(1+x^4)}{(x-sin \\ x)(2x-x^3)} + e^{-|x|}\\\\)எனில் f",
	"choices": [{
		"value": "ஒரு ஒற்றைப்படைச் சார்பு "
	}, {
		"value": "ஒற்றைப்படையுமல்ல இரட்டைப்படையுமல்ல"
	}, {
		"value": "ஒரு இரட்டைப்படைச் சார்பு)",
		"answer": true
	}, {
		"value": "ஒற்றைப்படை மற்றும் இரட்டைப்படைச் சார்பு"
	}]
}