@baseUrl = http://localhost:8080/api
@username = tom
@password = password

### Login to get auth token
# @name auth_res
POST {{baseUrl}}/auth/login
Content-Type: application/json

{  
  "userName": "{{username}}@email.com",
  "password": "{{password}}"
}

### Login to get auth token
# @name auth_res
POST {{baseUrl}}/auth/register
Content-Type: application/json
Authorization: Bearer {{auth_res.response.body.$.registrationToken}}

{
  "name":"{{username}}",
  "dob":"2000-10-10"
}

### Create a Question
POST {{baseUrl}}/questions/CHOOSE_THE_BEST/cse/databases/rdbms
Authorization: Bearer {{auth_res.response.body.$.authToken}}
Content-Type: application/json

{
  "question": "What is Postgress ?",
  "explanation": "",
  "type": "CHOOSE_THE_BEST",
  "choices": [
    {
      "cValue": "Document Database"
    },
    {
      "cValue": "Relational Database",
      "isAnswer": true
    },
    {
      "cValue": "Key Value Store"
    },
    {
      "cValue": "None of the above"
    }
  ]
}

### List Questions
GET {{baseUrl}}/questions/cse/databases/rdbms
Authorization: Bearer {{auth_res.response.body.$.authToken}}
Content-Type: application/json

### Logout
POST {{baseUrl}}/auth/logout
Authorization: Bearer {{auth_res.response.body.$.authToken}}