@base = http://localhost:8080/api

#### Login
# @name login 
POST {{base}}/auth/login
Content-Type: application/json

{
    "userName": "tom",
    "password": "password"
}

### Listing boards  
GET {{base}}/boards
Authorization: Bearer {{login.response.body.authToken}}
Content-Type: application/json

#### Refresh
# @name login 
POST {{base}}/auth/refresh
Authorization: Bearer {{login.response.body.authToken}}
Content-Type: application/json

{
    "token": "{{login.response.body.refreshToken}}"
}

#### Logout
POST {{base}}/auth/logout
Authorization: Bearer {{login.response.body.authToken}}
Content-Type: application/json