@base = http://localhost:8080/api

#### Login
# @name login 
POST {{base}}/auth/signup
Content-Type: application/json

{
    "email": "tom@email.com",
    "password": "password",
    "imageUrl": "/images/tom.png"
}

#### Login
# @name login 
POST {{base}}/auth/login
Content-Type: application/json

{
    "userName": "tom@email.com",
    "password": "password"
}

### Create Board  
POST {{base}}/boards
Authorization: Bearer {{login.response.body.authToken}}
Content-Type: application/json

{
  "title": "Sports",
  "description": "Sports related practices"
}

### Create Board  
POST {{base}}/boards
Authorization: Bearer {{login.response.body.authToken}}
Content-Type: application/json

{
  "title": "Entertainment",
  "description": "Sports related practices"
}

### Listing boards  
GET {{base}}/boards
Authorization: Bearer {{login.response.body.authToken}}
Content-Type: application/json

### Get Me  
GET {{base}}/auth/me
Authorization: Bearer {{login.response.body.authToken}}
Content-Type: application/json

#### Refresh
# @name login 
POST {{base}}/auth/refresh
Authorization: Bearer {{login.response.body.authToken}}
Content-Type: application/json

{
    "token": "{{login.response.body.refreshToken}}"
}

#### Logout
POST {{base}}/auth/logout
Authorization: Bearer {{login.response.body.authToken}}
Content-Type: application/json