@base = http://localhost:8080/api 

#### Login 
# @name login 
POST {{base}}/auth/login
Content-Type: application/json

{
    "userName": "tom@email.com",
    "password": "password"
}

#### Create Category
POST {{base}}/categories
Authorization: Bearer {{login.response.body.authToken}}
Content-Type: application/json

{
  "id" : "botany",
  "title": "Botany"
}

#### Create Category
POST {{base}}/categories
Authorization: Bearer {{login.response.body.authToken}}
Content-Type: application/json

{
  "id" : "reproduction",
  "title": "Reproduction"
}

#### Get Questions for a Book
# @name questions
GET {{base}}/books/questions/botany/reproduction
Authorization: Bearer {{login.response.body.authToken}}
Content-Type: application/json

#### Create Question
# @name question
POST {{base}}/books/questions/CHOOSE_THE_BEST/botany/reproduction
Authorization: Bearer {{login.response.body.authToken}}
Content-Type: application/json

{
  "question": "Who is the 2 cricketer?",
  "explanation": "Who is the 2 cricketer?",
  "type": "CHOOSE_THE_BEST",
  "choices": [{
    "value": "Sachin"
  }, {
    "value": "Dhoni"
  }, {
    "value": "Dravid",
    "answer": true
  }, {
    "value": "Kapil"
  }]
}

#### Update Question
PUT {{base}}/books/questions/CHOOSE_THE_BEST/{{question.response.body.id}}/botany/reproduction
Authorization: Bearer {{login.response.body.authToken}}
Content-Type: application/json
Accept-Language: ta

{
  "question": "யார் நல்ல கிரிக்கெட் வீரர் ?",
  "type": "CHOOSE_THE_BEST",
  "explanation": "",
  "choices": [{
    "id" : "{{question.response.body.choices[0].id}}",
    "value": "சச்சின்"
  }, {
    "id" : "{{question.response.body.choices[1].id}}",
    "value": "டோனி"
  }, {
    "id" : "{{question.response.body.choices[2].id}}",
    "value": "டிராவிட்",
    "answer": true
  }, {
    "id" : "{{question.response.body.choices[3].id}}",
    "value": "கபில்"
  }]
}




#### List Questions
GET {{base}}/books/questions/botany/reproduction
Authorization: Bearer {{login.response.body.authToken}}
Content-Type: application/json


#### List Questions for Locale
GET {{base}}/books/questions/botany/reproduction
Authorization: Bearer {{login.response.body.authToken}}
Content-Type: application/json
Accept-Language: ta


#### Get Practice for Tamil
POST {{base}}/auth/logout
Authorization: Bearer {{login.response.body.authToken}}
Content-Type: application/json