@baseUrl = http://localhost:3000/api
@username = jerry@email.com
@password = jerrypassword

### Login to get auth token
# @name auth_res
POST {{baseUrl}}/auth/login
Content-Type: application/json

{  
  "userName": "{{username}}",
  "password": "{{password}}"
}

### Create a Question
POST {{baseUrl}}/questions/CHOOSE_THE_BEST/cse/databases/rdbms
Authorization: Bearer {{auth_res.response.body.$.authToken}}
Content-Type: application/json

{
  "question": "What is Postgress ?",
  "explanation": "",
  "type": "CHOOSE_THE_BEST",
  "choices": [
    {
      "value": "Document Database"
    },
    {
      "value": "Relational Database",
      "answer": true
    },
    {
      "value": "Key Value Store"
    },
    {
      "value": "None of the above"
    }
  ]
}

### Get Questions using the auth token
GET {{baseUrl}}/questions/cse/databases/rdbms
Authorization: Bearer {{auth_res.response.body.$.authToken}}
Content-Type: application/json


### Logout
POST {{baseUrl}}/auth/logout
Authorization: Bearer {{auth_res.response.body.$.authToken}}