name: Reusable workflow example

on:
  workflow_call:
    secrets:
      HOST:
        required: true
      USERNAME:
        required: true
      PASSWORD:
        required: true
      TARGET_DIR:
        required: true
      QUESTIONS_DIR:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        hugo-version:
          - '0.117.0'
    steps:
      - uses: actions/checkout@v2

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: ${{ matrix.hugo-version }}
          extended: true

      - name: Download Theme
        run: |
          git clone https://github.com/techatpark/gurukulam
          find gurukulam/site/content.*/** -maxdepth 0 -type d -not -name courses -not -name "books"  -exec rm -rf {} \;
          rm -rf gurukulam/site/static/ && rm -rf gurukulam/site/layouts/index.html

      - name: Build Books
        run: |
          BOOK_PATH=$(git config --get remote.origin.url | cut -d. -f2 | cut -c 5-)
          for dir in content.*/; do mkdir -p temp/books/$BOOK_PATH && mv $dir/** temp/books/$BOOK_PATH && mv temp/** $dir/; done
          cp -rf content.* gurukulam/site/

      - name: Build Slides
        run: |
          SLIDE_PATH=$(git config --get remote.origin.url | cut -d. -f2 | cut -c 5-)
          for dir in slides/content.*/; do mkdir -p temp/courses/books/$SLIDE_PATH && mv $dir/** temp/courses/books/$SLIDE_PATH && mv temp/** $dir/; done
          cp -rf slides/content.* gurukulam/site/

      - name: Run Hugo
        working-directory: gurukulam/site
        run: env BUILD_PRODUCTION=Y hugo --themesDir ../..
 
      - name: Cleanup
        run: |
          rm -rf gurukulam/site/public/*.* && rm -rf gurukulam/site/public/tags && rm -rf gurukulam/site/public/en
          ls gurukulam/site/public

      - name: Deploy
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          source: "gurukulam/site/public"
          target: ${{ secrets.TARGET_DIR }}
          strip_components: 3

      - name: Upload Questions
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          source: "questions"
          target: ${{ secrets.QUESTIONS_DIR }}
